# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4a3aa6492d6d43e569084c47b58e8be3e02680d7909e9aaf0f9a2027632f96c5e901823ce71b65023cbfac35c790263a61b8a550c8617693d71ea7efdc56fa1

test:
  secret_key_base: 568815d5ae07abb0a69a1e672c174d804c91e771dabec57e67f2cb43b50b985516526ec794b56ec283e16bbb069f7cf02531b2153dd1dc0cc5b01f05ab6e3d16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
